# Generated by Django 4.1.6 on 2023-02-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_create_model_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='source',
            field=models.CharField(default='', max_length=25),
        ),
    ]
