# Generated by Django 4.1.7 on 2023-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_rename_sell_rate_sale_alter_source_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='code_name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
