# Generated by Django 4.1.7 on 2023-04-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_source_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='code_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
