# Generated by Django 4.1.7 on 2023-05-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0012_alter_source_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresponselog',
            name='request_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'PATCH'), (5, 'DELETE')], default=1),
        ),
    ]
