# Generated by Django 4.1.7 on 2023-05-07 10:04

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0013_alter_requestresponselog_request_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='logo',
            field=models.FileField(blank=True, default='', null=True, upload_to=currency.models.source_logo_path),
        ),
    ]
